### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by schiederme**
Hey there,
Awesome package!

I have updated the dependencies and had to add a new .gitignore because of my setup. 

Tests run without a problem.

I hope this helps. Ff I should change anything, please hit me up!

### CODE REVIEW

**Review by bpolaszek — CHANGES_REQUESTED** [review]
Hello @schiederme,

Thank you for supporting this library!
I'm OK with the upgrade - can you just commit without the `.gitignore` change? You can create a global `.gitignore` on your computer to address this kind of things: https://sebastiandedeyne.com/setting-up-a-global-gitignore-file/

Thank you,
Ben

**Review by bpolaszek — APPROVED** [review]

**Comment by bpolaszek** [comment]
Thank you @schiederme!

Just 1 thing again, can you remove your `composer.lock` from the PR? As this repository is a dependency, not a project, we don't want people to enforce a too much specific version.

**Comment by schiederme** [comment]
Everything done :-)

**Comment by bpolaszek** [comment]
Brilliant! 👍 

(CI fails, but I have to migrate it to Github Actions first, will keep you posted)

**Comment by bpolaszek** [comment]
Wow, that's weird, Github closed that one when I merged `bpolaszek:build/github-actions` into `master`. Can you please open a new PR?
One thing that must be fixed to pass CI: bump PHP to `>=7.3` in `composer.json`, otherwise it's a fantastic mess to keep compatibility from `7.1` and the different phpunit versions. Basically you can rebase on `master` for that, which has been updated.
I'll tag a new minor release once OK.

Thank you!
Ben

**Pull request closed without merging**
